### ISSUE TITLE
prefix attributes names

### ISSUE THREAD

**Issue by nicomott** [cachapa/ExpandableLayout#10]
There is a collision with the attribute orientation when using this lib with others that also define an attribute "orientation". This would be fixed by renaming "orientation" into "el_orientation"

**Comment by cachapa** [comment]
I was actually hoping to reuse the "orientation" tag from LinearLayout. At least it's not causing any collisions for me, but I don't know if I did it correctly.

Are you getting compilation errors?

**Comment by nicomott** [comment]
Yes, I can't compile. It might work on your project if you don't have an other lib trying to define the same tag. 
If you want to reuse the android orientation, I think you just have to use `<attr name="android:orientation"/>`

**Comment by cachapa** [comment]
Thanks for the suggestion, it worked perfectly.

I'll push the changes shortly and publish an update on jcenter.
