### ISSUE TITLE
Expanding last visible item

### ISSUE THREAD

**Issue by eerikk** [cachapa/ExpandableLayout#13]
In RecyclerView, when I'm expanding my last visible element, it expands out of the screen. When I want to see the expanded layout I need to manually scroll RecyclerView. Is there an option to automatically scroll the RecyclerView so when I open last visible element it automatically scrolls the recyclerView as well?

**Comment by cachapa** [comment]
I don't think this is something which the ExpandableLayout can do, but rather the parent View (in your case the RecyclerView) has to check.

If I'm not mistaken, there's a method in RecyclerView that scrolls to a given item so that it is completely visible. That should fix your issue.

**Comment by cachapa** [comment]
See 653253f
