### ISSUE TITLE
How to put an indicator if it was expand or collapse ?

### ISSUE THREAD

**Issue by ultrabuckner** [cachapa/ExpandableLayout#14]
Implement same thing like website accordion. It has an icon as indicator to whether its expand or collapse.

Here an example :
https://roaderapp.com/faq.html

**Comment by cachapa** [comment]
Set a listener using `setOnExpansionUpdateListener(OnExpansionUpdateListener listener)`.

The callback gives you the expansion ratio as a float from 0 (collapsed) to 1 (expanded). Simply set your bitmap accordingly.

**Comment by ultrabuckner** [comment]
Do you have any example ?

**Comment by ultrabuckner** [comment]
Thanks for quick reply.
