### ISSUE TITLE
Expand Horizontal right to left

### ISSUE THREAD

**Issue by tam0407** [cachapa/ExpandableLayout#16]
Hi, I am currently using your library for a layout that expands vertically in my project, and it works perfectly. But now I have a feature that needs another layout to be expanded from right to left (horizontal). 
I can achieve this by using the old `ExpandableLinearLayout` with `android:orientation="horizontal"` and `android:layoutDirection="rtl"`, but there is a glitch in the animation and it's deprecated anyway.
I try to use `ExpandableLayout` but it somehow expands the layout from the middle, please help.

**Comment by cachapa** [comment]
First of all, I would strongly recommend against using `ExpandableLinearLayout` and am unable to offer any support if you choose to do so.

Having said that, you found a bug in the library, so thanks! :smile:
I'll try to get it fixed as soon as possible.

**Comment by tam0407** [comment]
Wow, that was fast. It works like a charm with v2.6. Thanks a lot for that 👍

**Comment by cachapa** [comment]
No problem, thanks for the report and for letting me know the fix works.
