### ISSUE TITLE
[Feature Request] New propriety tools:el_expanded

### ISSUE THREAD

**Issue by powerhcm8** [cachapa/ExpandableLayout#17]
This propriety would control if the expandablelayout is open or close only on android studio's preview similar to textview's tools:text.

**Comment by cachapa** [comment]
Unfortunately it seems that Android Studio doesn't support custom attributes with the tools namespace.

When (if ever) support is implemented it will probably be transparent. I'm closing this issue for now and it can be reopened if that's not the case.

**Comment by powerhcm8** [comment]
And something like app:el_expanded_in_editor and this code below would work?

`
if (!isInEditMode()) {
   expansion = a.getBoolean(R.styleable.ExpandableLayout_el_expanded_in_editor, false) ? 1 : 0;
}
`

**Comment by cachapa** [comment]
I'm not too fond of that idea.

I think it would be easier (and a lot cleaner) for you to extend `ExpandableLayout` and do that check from your expanded class:
``` java
public class MyExpandableLayout extends ExpandableLayout {
    public MyExpandableLayout(Context context, AttributeSet attrs) {
        super(context, attrs);
        if (isInEditMode()) {
            setExpansion(1);
        }
    }
}
```
