### ISSUE TITLE
Large Content Hide Remaining Accordian

### ISSUE THREAD

**Issue by kushanshah11** [cachapa/ExpandableLayout#18]
Hi cachapa,
 when i have multiple record in one Accordion in recyclerview it will hide other Accordion,

how can i show other accordion while scroll end of particular Accordion.
Here i attach my screen like i have 4 Accordion and in 2nd accordion i have multiple data it will hide 3rd and 4th accordion can you please suggest me while scroll end up i m able to see header of 3rd and 4th accordion .

Thanks in advance.

![capture](https://cloud.githubusercontent.com/assets/18567763/21983224/305a638c-dc16-11e6-8efd-9ff77c1db937.PNG)
![capture1](https://cloud.githubusercontent.com/assets/18567763/21983228/31f5c556-dc16-11e6-9c5e-d170119ecef5.PNG)

**Comment by cachapa** [comment]
I'm not sure I understand your question clearly, but it seems you're looking for general dev support.
Unfortunately I can't spare the time to give individual technical support. For that please use http://stackoverflow.com

**Comment by kushanshah11** [comment]
Hi cachapa,

i update my question here , i have four accordion info,sensor etc,  while i have recyclerview in last three accordion now my issue is when i open second accordion it will hide last two, lets have 50 rows in second accordion after scroll 50 rows i m not able to see last two accordion.


here i attched updated issue which i faced....    

![capture](https://cloud.githubusercontent.com/assets/18567763/22009137/11f96e06-dca7-11e6-97b7-313c2d626da3.PNG)
![capture1](https://cloud.githubusercontent.com/assets/18567763/22009138/11fd06f6-dca7-11e6-9fed-1de5902451a2.PNG)

Hope you understand issue and give me resolution for same.

Thanks in Advance.

**Comment by cachapa** [comment]
This doesn't look like a ExpandableLayout issue, but rather a problem with how your layouts are structured.

Try removing the ExpandableLayout from one of the "accordions" and you will most likely have the same problem. Again, this is not an Android dev support forum, please direct these questions to a more appropriate place.
