### ISSUE TITLE
Error inflating class

### ISSUE THREAD

**Issue by joaovictortinoco** [cachapa/ExpandableLayout#21]
Hi, 

When i use ExpandableLayout with RecyclerView, the Android doesn't allow to inflate class. 

The error report: 

"FATAL EXCEPTION: main android.view.InflateException: Binary XML file line #38: Error inflating class net.cachapa.expandablelayout.ExpandableLayout" 

And points to the following line of my code: 

`View view = LayoutInflater.from(parent.getContext()).inflate(R.layout.expandable_minha_consulta_row, parent, false);`

**Comment by cachapa** [comment]
I'm afraid that's not enough information for me to figure out what the problem is. Can you share the code (layout and related java source)?

Have you tried following the demo example?
https://github.com/cachapa/ExpandableLayout/blob/master/demo/src/main/java/net/cachapa/expandablelayoutdemo/RecyclerViewFragment.java

**Comment by joaovictortinoco** [comment]
Ok! 

This is my Adapter class: 

`package br.com.medflex.adapters;

import android.support.v7.widget.RecyclerView;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.view.animation.OvershootInterpolator;
import android.widget.ImageButton;
import android.widget.TextView;

import net.cachapa.expandablelayout.ExpandableLayout;

import java.util.List;

import br.com.medflex.R;
import br.com.medflex.utils.MinhaConsulta;

public class MinhaConsultaAdapter extends RecyclerView.Adapter<MinhaConsultaAdapter.ViewHolder> {
    private int UNSELECTED = -1;

    private RecyclerView recyclerView;
    private int selectedItem = UNSELECTED;
    private List<MinhaConsulta> consultas;

    public MinhaConsultaAdapter(RecyclerView recyclerView, List<MinhaConsulta> consultas) {
        this.recyclerView = recyclerView;
        this.consultas = consultas;
    }

    @Override
    public ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        View view = LayoutInflater.from(parent.getContext())
                .inflate(R.layout.expandable_minha_consulta_row, parent, false);
        return new ViewHolder(view);
    }

    @Override
    public void onBindViewHolder(ViewHolder holder, int position) {
        holder.bind(position);
    }

    @Override
    public int getItemCount() {
        return consultas.size();
    }

    public class ViewHolder extends RecyclerView.ViewHolder implements View.OnClickListener {

        private ExpandableLayout expandableLayout;
        private TextView especialidade, data, hora, local;
        private ImageButton imgExpand;
        private int position;

        public ViewHolder(View itemView) {
            super(itemView);

            expandableLayout = (ExpandableLayout) itemView.findViewById(R.id.expandable_recycler);
            expandableLayout.setInterpolator(new OvershootInterpolator());

//            imgExpand = (ImageButton) itemView.findViewById(R.id.img_expandable);

            especialidade = (TextView) itemView.findViewById(R.id.txt_consulta_especialidade);
            data = (TextView) itemView.findViewById(R.id.txt_consulta_data);
/*
            hora = (TextView) itemView.findViewById(R.id.txt_consulta_hora);
            local = (TextView) itemView.findViewById(R.id.txt_consulta_local);

            imgExpand.setOnClickListener(this);
*/
            especialidade.setOnClickListener(this);
        }

        public void bind(int position) {
            this.position = position;

//            imgExpand.setSelected(false);
            especialidade.setSelected(false);
            expandableLayout.collapse(false);

            especialidade.setText(consultas.get(position).getEspecialidade());
            data.setText(consultas.get(position).getData());
//            hora.setText(consultas.get(position).getHora());
//            local.setText(consultas.get(position).getLocal());

        }

        @Override
        public void onClick(View v) {
            ViewHolder viewHolder = (ViewHolder) recyclerView.findViewHolderForAdapterPosition(selectedItem);

            if (viewHolder != null) {
                viewHolder.imgExpand.setSelected(false);
                viewHolder.expandableLayout.collapse();
            }

            if (position == selectedItem) {
                selectedItem = UNSELECTED;
            } else {
                imgExpand.setSelected(true);
                expandableLayout.expand();
                selectedItem = position;
            }

        }
    }
}
`

And that's my layout file:

`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:orientation="vertical">

    <TextView
        android:id="@+id/txt_consulta_especialidade"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:elevation="6dp"
        android:foreground="?selectableItemBackground"
        android:padding="@dimen/activity_horizontal_margin"
        android:text="Especialidade 01" />

    <net.cachapa.expandablelayout.ExpandableLayout
        android:id="@+id/expandable_recycler"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_below="@+id/img_expandable"
        app:el_duration="300"
        app:el_expanded="false">

        <TextView
            android:id="@+id/txt_consulta_data"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:text="Data" />
    </net.cachapa.expandablelayout.ExpandableLayout>

</LinearLayout>`

**Comment by cachapa** [comment]
Your layout file is incomplete.
Please post the exact code, otherwise it's almost impossible to figure out where the problem is.

**Comment by joaovictortinoco** [comment]
It was an edition error. Sorry about it. Updated!

**Comment by cachapa** [comment]
Sorry I couldn't replicate the issue.
Would it be possible to share a small project with the problem?

**Comment by joaovictortinoco** [comment]
Yep, i'll share with you soon.

**Comment by joaovictortinoco** [comment]
Check it out: https://github.com/joaovictortinoco/mobix-medflex-android/tree/medflex-v1

**Comment by cachapa** [comment]
I actually was looking for a small project that just shows the problem. I couldn't even find the screen where you use the recyclerview.

**Comment by joaovictortinoco** [comment]
Sorry man, the project is huge. 

Look again, please.

You should look for the references in fragment folder, "MinhaConsultaFragment.java" that points to the layout. And if you run the application, the error log will be the first.

**Comment by cachapa** [comment]
Sorry but I don't have the time to dig through so much code.

The use case you mention works fine in the demo project, which you seem to have copied.
If you can't produce a compact example that shows the problem I'll have to assume the issue lies in your changes and close this report.

**Comment by joaovictortinoco** [comment]
Ok, then. Thanks anyway.
