### ISSUE TITLE
show selected item on screen properly not hide in up or down

### ISSUE THREAD

**Issue by rajam1215** [cachapa/ExpandableLayout#23]
if item click in recycler view then selected item show properly not hide at bottom or not hide top on screen.
how to solve

**Comment by cachapa** [comment]
Sorry, but this issue tracker is meant for bug reports of feature requests specifically for the ExpandableLayout lib.
The problem you mention isn't caused by this library, but is rather a the more general problem of RecyclerView item visibility when the content changes.
For that type of support that please try http://stackoverflow.com

**Comment by rajam1215** [comment]
please give me any solution if u have

**Comment by rajam1215** [comment]
this is my layout

recycler items layout

<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/tools"
    xmlns:card_view="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:orientation="vertical">

    <android.support.v7.widget.CardView
        android:id="@+id/card_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_gravity="center"
        android:layout_margin="@dimen/card_margin"
        card_view:cardCornerRadius="@dimen/card_album_radius">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="vertical">

            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:background="@color/card_gray"
                android:orientation="horizontal"
                android:weightSum="4">

                <de.hdodenhof.circleimageview.CircleImageView
                    android:id="@+id/deals_app_image"
                    android:layout_width="0dp"
                    android:layout_height="65dp"
                    android:layout_marginBottom="8dp"
                    android:layout_marginLeft="5dp"
                    android:layout_marginTop="8dp"
                    android:layout_weight="0.8"
                    android:background="@color/card_gray" />

                <LinearLayout
                    android:layout_width="0dp"
                    android:layout_height="wrap_content"
                    android:layout_gravity="center"
                    android:layout_weight="1.8"
                    android:orientation="vertical"
                    android:padding="14dp">

                    <TextView
                        android:id="@+id/deals_app_name"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:gravity="left"
                        android:text="@string/appname"
                        android:textColor="@color/dark_gray"
                        android:textSize="20sp" />

                    <TextView
                        android:id="@+id/deals_app_detail"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:gravity="left"
                        android:text="@string/app_des"
                        android:textColor="@color/dark_gray"
                        android:textSize="10sp" />

                </LinearLayout>

                <LinearLayout
                    android:layout_width="0dp"
                    android:layout_height="match_parent"
                    android:layout_weight="0.8"
                    android:gravity="center"
                    android:orientation="vertical">

                    <TextView
                        android:id="@+id/deals_app_price"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_gravity="right"
                        android:textColor="@color/orange"
                        android:textSize="26sp"
                        android:visibility="visible" />

                </LinearLayout>

                <ImageView
                    android:id="@+id/overflow"
                    android:layout_width="0dp"
                    android:layout_height="wrap_content"
                    android:layout_gravity="center"
                    android:layout_weight="0.6"
                    android:background="@color/card_gray"
                    android:src="@drawable/dropdown" />

            </LinearLayout>

            <net.cachapa.expandablelayout.ExpandableLayout
                android:id="@+id/expandable_layout"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:background="@color/card_gray"
                app:el_duration="300"
                app:el_expanded="false">

                <LinearLayout
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="12dp"
                    android:layout_marginRight="12dp"
                    android:orientation="vertical">

                    <android.support.v7.widget.RecyclerView
                        android:id="@+id/detail_recycler_view"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:nestedScrollingEnabled="false" />

                    <View
                        android:layout_width="match_parent"
                        android:layout_height="2dp"
                        android:layout_marginTop="15dp"
                        android:background="@color/view_gray" />

                    <LinearLayout
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:layout_marginTop="15dp"
                        android:orientation="horizontal"
                        android:weightSum="2">

                        <TextView
                            android:id="@+id/deals_app_receive"
                            android:layout_width="0dp"
                            android:layout_height="wrap_content"
                            android:layout_gravity="center"
                            android:layout_weight="1.5"
                            android:gravity="start"
                            android:text="@string/receive"
                            android:textColor="@color/orange"
                            android:textSize="28sp" />

                        <TextView
                            android:id="@+id/deals_app_amount"
                            android:layout_width="0dp"
                            android:layout_height="wrap_content"
                            android:layout_gravity="center"
                            android:layout_weight="0.5"
                            android:gravity="end"
                            android:textColor="@color/orange"
                            android:textSize="28sp" />

                    </LinearLayout>

                    <Button
                        android:id="@+id/getdeal"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:layout_marginBottom="15dp"
                        android:layout_marginTop="15dp"
                        android:background="@color/orange"
                        android:text="@string/get_deal"
                        android:textColor="@color/white"
                        android:textSize="18sp" />

                </LinearLayout>

            </net.cachapa.expandablelayout.ExpandableLayout>

        </LinearLayout>

    </android.support.v7.widget.CardView>

</LinearLayout>







and recycler view

<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/white"
    app:layout_behavior="@string/appbar_scrolling_view_behavior"
    tools:context=".Activity.MainActivity">

    <android.support.v7.widget.RecyclerView
        android:id="@+id/deals_recycler_view"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:clipToPadding="false"
        android:scrollbars="vertical" />

    <ProgressBar
        android:id="@+id/progressbar_deal"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_centerInParent="true"
        android:layout_gravity="center" />

</RelativeLayout>
