### ISSUE TITLE
Is it possible to collapse when click on "expanded" content

### ISSUE THREAD

**Issue by hasancse91** [cachapa/ExpandableLayout#24]
I'm using RecyclerView. When I click on an Item the content (Relative Layout) is expanded well. To collapse this expanded content I have to click on **Item**. 

Is it possible to collapse the expanded content after clicking on it (in my case click on a Relative Layout).

Thank you for making this awesome library. <3

**Comment by cachapa** [comment]
Sure, you just need to call ExpandableLayout.collapse(), it doesn't really matter where you're calling it from.
In your case you just need to set a click listener on your content.

**Comment by hasancse91** [comment]
Thank you for your rapid response. My problem is solved. :+1:
