### ISSUE TITLE
How to stop. to go upper side the item in screen. when click on recycler view any item.

### ISSUE THREAD

**Issue by rajam1215** [cachapa/ExpandableLayout#25]
I think it is happen when click the any item. many time it expand from bottom of item. some time it expand from top side from item. and when i click first item in recycler view. it expand top side from item. and some time it expand bottom side. most time it expand top side.  when it expand top side from item. this time the first item expanded view hide behind the toolbar. so this is the error i think. if u have any solution then give me. plaese give any solution

**Comment by cachapa** [comment]
I already told you that this issue tracker isn't the right place to ask for support.
If you don't stop opening issues I will be forced to block you.

**Comment by rajam1215** [comment]
hay man calm down. i just want from you solution. if u don't do that then simply say. i cant do that.
u are developer. i thing this type of query's is good for your knowledge. and good for others. i u cant. so i never ask u again
