### ISSUE TITLE
Can I expand layout Vertically and Bottom up ?

### ISSUE THREAD

**Issue by tam0407** [cachapa/ExpandableLayout#27]
I need to animate the layout bottom up. Can I do this with the current version? Please help, thanks.

**Comment by cachapa** [comment]
I'm not sure I understood the question correctly, but have you tried playing with the parallax option?
```
app:el_parallax="0"
```
It takes float values between 0 and 1. Try it to see if it solves your problem.

**Comment by tam0407** [comment]
Oh I mean I can expand my layout vertically from `top` to `bottom` with default setting like this:
```
app:el_duration="300"
app:el_expanded="false"
```
But now the app requires me to expand it from `bottom` to `top`. 

I try to find a demo and I think this may help, it's an animation for web, hit `run` to start:
http://codepen.io/sgorneau/pen/EjBzwB

**Comment by cachapa** [comment]
This issue tracker is meant for tracking bugs and feature requests for the library.
For support please use StackOverflow. Just create a post there and I'll gladly answer it (post a link here once it's up).
