### ISSUE TITLE
while using expandale layout as  recyclerview item 

### ISSUE THREAD

**Issue by hirenpatel868** [cachapa/ExpandableLayout#30]
issue : on Item click it open at bottm of all item in recyclerview
expected result it should open bottom of  clicked item.

**Comment by cachapa** [comment]
It does open, just that the expanded layout isn't visible unless you scroll the recycler view down.
Performing that scroll is the responsibility of the implementation.

**Comment by hirenpatel868** [comment]
in my project i  implement expandable layout with recycler same as demo but...in my project each item contains recyclerview inside.

**Comment by cachapa** [comment]
I'm not sure that would work as you'd expect it to. Try replacing ExpandableLayout with a FrameLayout and see if you're getting the behaviour you want.
