### ISSUE TITLE
Feature request: Listener for state changed

### ISSUE THREAD

**Issue by tam0407** [cachapa/ExpandableLayout#32]
Hi, can we have a listener for state changed ?. Something like: onExpaned, onCollapsed...

I tried to use onExpansionUpdateListener but the `expansionFraction` param won't return the correct value 0 or 1, and it's performance related if I have to check `expansionFraction` many times during the animation.

**Comment by cachapa** [comment]
Thanks for the feedback, I'll work on it.

Regarding checking the `expandedFraction`, it should always return the correct value, unless you're using a Bounce or Overshoot interpolator. If that's not the case then it might be a bug which I'd like to fix.

By the way, checking the `expansionFraction` value in the listener should have no impact on performance unless you're doing something else in every check. A float compare is trivial work for a modern (even mobile) CPU.

**Comment by tam0407** [comment]
From my check, the `expansionFraction` param returns value from 0 to almost 1 (~0.9998...), but not 1, so I need to do some extra work to assume that it's closest to 1. A set of listeners to specific states would be very helpful. Anyway, thanks for the information.

**Comment by cachapa** [comment]
You're right, I just checked the code and internally I also had to work around the fact that the animator doesn't always reach 1.
I've opened ticket #33 to track this.

**Comment by Savrov** [comment]
Hi, i've tested my code and it works fine. 0 and 1 were reached w/o problems.

`if (holder.dataBody.isExpanded()) {
                    Log.d(TAG, "data body was isExpanded");
                    holder.dataBody.collapse();
                    holder.dataBody.setOnExpansionUpdateListener(new ExpandableLayout.OnExpansionUpdateListener() {
                        @Override
                        public void onExpansionUpdate(float expansionFraction) {
//                            Log.d(TAG, "collapsing expansionFraction" + expansionFraction);
                            if (expansionFraction == 0) {
                                Log.d(TAG, "collapsing expansionFraction" + expansionFraction);
                                Log.d(TAG, "dataHeaderExpanded collapsing");
                                holder.dataHeaderExpanded.collapse();
                            }
                        }
                    });
                } else {
                    Log.d(TAG, "data body was isCollapsed");
                    holder.dataHeaderExpanded.expand();
                    holder.dataHeaderExpanded.setOnExpansionUpdateListener(new ExpandableLayout.OnExpansionUpdateListener() {
                        @Override
                        public void onExpansionUpdate(float expansionFraction) {
//                            Log.d(TAG, "expanding expansionFraction" + expansionFraction);
                            if (expansionFraction == 1) {
                                Log.d(TAG, "expanding expansionFraction" + expansionFraction);
                                Log.d(TAG, "dataBody expending");
                                holder.dataBody.expand();
                            }
                        }
                    });
                }`

The result is:
- to open 

> data body was isCollapsed
> expanding expansionFraction1.0
> dataBody expending

- to close

> data body was isExpanded
> collapsing expansionFraction0.0
> dataHeaderExpanded collapsing

**Comment by cachapa** [comment]
@Savrov I think the problem doesn't occur on all interpolators. As far as I remember it works fine on the default one, which would explain why it's working for you.

**Comment by cachapa** [comment]
Fixed in 2.9

**Comment by tam0407** [comment]
Thanks a lot, it works now
