### ISSUE TITLE
Make item fully visible after expanding

### ISSUE THREAD

**Issue by Savrov** [cachapa/ExpandableLayout#34]
I just noticed that if i scroll to the last item and click to expand, then part of the opened view is invisible. How can i scroll down to make the whole view visible?

**Comment by cachapa** [comment]
ExpandableLayout knows nothing about the layout where it's contained, so it can't know if the expanded area is visible to the user or not.

This question comes up often enough that I'll just implement a solution in the demo.

**Comment by cachapa** [comment]
See 653253f

**Comment by Savrov** [comment]
@cachapa is it a good practise to let **adapter** know about **recyclerView**?
`recyclerView.setAdapter(adapter(recyclerView))`
