### ISSUE TITLE
Releases page out of date

### ISSUE THREAD

**Issue by athornz** [cachapa/ExpandableLayout#39]
Hi,

It really confused me that the releases page was out of date - I often look there in github repos to find the latest version. Perhaps if you are no longer using it you should delete the existing releases?

**Comment by cachapa** [comment]
Thanks for the report. You're right that it's missleading.

I started to use github releases because I was using jitpack for distribution, but forgot to remove them when I moved to jcenter.

I've deleted all releases and tags.
