### ISSUE TITLE
Make CardView fully invisible after expanding

### ISSUE THREAD

**Issue by Nidheeshkp** [cachapa/ExpandableLayout#41]
if i scroll to the Expandable Layout Card view not scroll down

**Comment by cachapa** [comment]
That is the parent layout's reponsibility. ExpandableLayout shouldn't have to know about its parent layout, or if it's scrolled into view.

You can use the ExpandableLayout listener to check for changes in size and scroll the parent layout accordingly.

**Comment by Nidheeshkp** [comment]
Thank you its solved
