### ISSUE TITLE
Auto-scroll to the bottom in the demo

### ISSUE THREAD

**Issue by DanChaltiel** [cachapa/ExpandableLayout#47]
When using the library with a RecycleView, at startup and whenever you update your adapter, it will automatically scroll to the bottom of the recycleview.

Not a big deal, you just have to add the check of the state in the [RecyclerViewFragment](https://github.com/cachapa/ExpandableLayout/blob/master/demo/src/main/java/net/cachapa/expandablelayoutdemo/RecyclerViewFragment.java) to prevent it.

        @Override
        public void onExpansionUpdate(float expansionFraction, int state) {
            if(state!=ExpandableLayout.State.COLLAPSED)
                recyclerView.smoothScrollToPosition(getAdapterPosition());
        }

Actually this is not really an issue, but I think this can prevent some unexpected behaviour and still be consistent to the general case.

**Comment by cachapa** [comment]
I don't understand. What does this fix?

**Comment by DanChaltiel** [comment]
Oops sorry, I missed my first sentence, I edited my comment

**Comment by cachapa** [comment]
Oh, I see now, thanks.
Should I fix it or do you want to make a pull request?

**Comment by cachapa** [comment]
Fixed in #48
