### ISSUE TITLE
Maximum height for expandable layout 

### ISSUE THREAD

**Issue by Nidhipiedistrict** [cachapa/ExpandableLayout#57]
How to set maximum height in expandable layout ? , is it possible?

**Comment by cachapa** [comment]
I don't understand the question. The expandable layout will grow to the height of it's child layout, so the maximum height is whatever you specify there.

**Comment by mgood7123** [comment]
he probably means for example, setting the ExpandableLayout inside a scrollView of a specified max height such that you can expand and scroll

**Comment by cachapa** [comment]
The expandable layout's max height is the max height of its child. I don't see why that wouldn't work in a scrollview.
