### ISSUE TITLE
Call API and set child view dynamically not displaying data when view scrolled 

### ISSUE THREAD

**Issue by Vaishnavi-optisol** [cachapa/ExpandableLayout#58]
Hi,

Kindly help me out for this situation.

I'm having recyclerview and on view click I used your library for expand and collapse. Issue here is expandableview layout has been created dynamically based on the API response. So on the time of API loading if I scroll the layout then the view not updated with the records from API.

I guess onBindView will get called on scroll and view got refreshed. But I'm not sure how to load childview data when scrolled.

I inserted "notifiyItemChanged" in OnBindHolder but it throws exception layout can be refreshed on scroll Illegal state exception. Kindly share your thoughts.

**Comment by cachapa** [comment]
Sorry but this is not an Android support forum. You might have more success if you direct your question to stackoverflow.com

Closing this since it isn't related to the project.
