### ISSUE TITLE
Only expand the Fixed content

### ISSUE THREAD

**Issue by WilbertTan** [cachapa/ExpandableLayout#65]
Lets say if I have a recycler view, which I want to show only 4 to 5 items at first, when the user clicks on a button (maybe a "View more" button), I want to expand the whole recycler view?
Is it possible to implement this?

**Comment by cachapa** [comment]
If I understood your question correctly you wouldn't use ExpandableLayout for something like this. In your example I would just load the first 4 or 5 items into the RecyclerView adapter, and load the rest when the user presses the button.

In any case I recommend you direct these types of questions to StackOverflow as you'll get much higher quality responses there than here.
