### ISSUE TITLE
Samsung s5, Android Version 6.0.1

### ISSUE THREAD

**Issue by marklw16** [cachapa/ExpandableLayout#66]
When the you expand layout, all the views below it are on top of each other. Any ideas how that could be fixed or what might cause it. 
Seems fine on Android 8.

**Comment by cachapa** [comment]
Can you attach a screenshot and the layout file?

**Comment by marklw16** [comment]
![screenshot_2018-07-16-10-40-35 1](https://user-images.githubusercontent.com/26220041/42871088-65ae5614-8a71-11e8-813d-3404a7234150.png)


So, in terms of layouts. Its basically a ScrollView, which contains a LinearLayout of orientation vertical. Then I inflate various other views and add those views to the LinerLayout. For the expandable section, it is essentially.....
`<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              xmlns:app="http://schemas.android.com/apk/res-auto"
              android:layout_width="match_parent"
              android:layout_height="match_parent"
              android:orientation="vertical">

  <RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="50dp">
    .....various image and text View's etc
  </RelativeLayout>

    <net.cachapa.expandablelayout.ExpandableLayout
        android:id="@+id/expandable_view"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:el_duration="1000"
        app:el_expanded="false"/>
    </LinearLayout>`

Then I add views to the expandable_view. Pretty much more RelativeLayout's

`<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="50dp">
     .....various image and text View's etc
  </RelativeLayout>`

**Comment by marklw16** [comment]
![sample](https://user-images.githubusercontent.com/26220041/42872140-0be106ba-8a74-11e8-9a7b-df8b179588be.png)

So, in terms of layouts. Its basically a ScrollView, which contains a LinearLayout of orientation vertical. Then I inflate various other views and add those views to the LinerLayout. For the expandable section, it is essentially.....
`


.....various image and text View's etc
<net.cachapa.expandablelayout.ExpandableLayout
    android:id="@+id/expandable_view"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    app:el_duration="1000"
    app:el_expanded="false"/>
</LinearLayout>`
Then I add views to the expandable_view. Pretty much more RelativeLayout's

<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android" android:layout_width="match_parent" android:layout_height="50dp"> .....various image and text View's etc </RelativeLayout>

**Comment by marklw16** [comment]
![sample](https://user-images.githubusercontent.com/26220041/42872181-27a1efc2-8a74-11e8-8ac7-50d197704e20.png)

So, in terms of layouts. Its basically a ScrollView, which contains a LinearLayout of orientation vertical. Then I inflate various other views and add those views to the LinerLayout. For the expandable section, it is essentially.....

`<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              xmlns:app="http://schemas.android.com/apk/res-auto"
              android:layout_width="match_parent"
              android:layout_height="match_parent"
              android:orientation="vertical">
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="50dp">
.....various image and text View's etc
</RelativeLayout>
<net.cachapa.expandablelayout.ExpandableLayout
    android:id="@+id/expandable_view"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    app:el_duration="1000"
    app:el_expanded="false"/>
</LinearLayout> `
Then I add views to the expandable_view. Pretty much more RelativeLayout's

`<RelativeLayout
xmlns:android="http://schemas.android.com/apk/res/android" 
android:layout_width="match_parent" 
android:layout_height="50dp"> 
.....various image and text View's etc 
</RelativeLayout>`

**Comment by marklw16** [comment]
Scratch that, it was my own fault. Used Relative views instead of linear vertical within the expandable layout.
