### ISSUE TITLE
Does this support scroll to position when expanded?

### ISSUE THREAD

**Issue by Ramachandran322** [cachapa/ExpandableLayout#76]
Thanks for the wonderful library!!

I'm wondering if this supports scroll to position when clicked a item. Currently I'm clicking an item and it's not scrolling to the appropriate position. User has to scroll up to view the expandable view. Any ideas to overcome this would be appreciable...

**Comment by NailPlay** [comment]
If I understand correctly, then this will help you:

https://github.com/cachapa/ExpandableLayout/issues/84

**Comment by cachapa** [comment]
Closing as this is not an issue with the library
