### ISSUE TITLE
Resetting child view when expanding other view

### ISSUE THREAD

**Issue by TamirHarouach** [cachapa/ExpandableLayout#79]
Hi, i have a child view that contain an EditText when i am writing something and move to other editText in other views the first one get reseted.

![Screenshot_1566389744](https://user-images.githubusercontent.com/20482925/63431029-dba6a680-c415-11e9-9a55-26011532224f.png)

**go to other view and write**

![Screenshot_1566389759](https://user-images.githubusercontent.com/20482925/63431071-f6791b00-c415-11e9-81e9-41bcd45ec58c.png)

**going back to the first one
nothing there**

![Screenshot_1566389764](https://user-images.githubusercontent.com/20482925/63431086-0133b000-c416-11e9-8add-68f557824618.png)

**Comment by TamirHarouach** [comment]
PS : if i goes back again and expand the view some time i got the text back

**Comment by cachapa** [comment]
Is this inside a recyclerview? In that case your previous view is being recycled.

**Comment by TamirHarouach** [comment]
Yes it's insided the RV, so i should use a listview instead ?

**Comment by cachapa** [comment]
I don't know your use case, so I can't give a recommendation. You might have more success asking that in StackOverflow.
In any case this isn't an issue with ExpandableLayout, so I'm closing this.
