### ISSUE TITLE
Is it possible to add expandable items dynamically? (when user taps on recyclerview item row)

### ISSUE THREAD

**Issue by pruthvirajha** [cachapa/ExpandableLayout#8]
If answer is yes. pls tell me how?

**Comment by cachapa** [comment]
That isn't currently possible since you can't set a view as expandable in code.

You can try `ExpandableLayout` in the `efficient_expansion` branch, but that's not available yet as a dependency - you'd have to compile the code yourself.

**Comment by pruthvirajha** [comment]
Thanks for the reply. I tried this way, I have added a linearlayout in xml and set the property expandable to ture, after that in runtime I have added items to that layout. It worked thanks
