### ISSUE TITLE
Can I expand multiple views at the same time?

### ISSUE THREAD

**Issue by pierrekhouryy** [cachapa/ExpandableLayout#82]
right now if I have an expanded view in a recycler view, and I try to expand another one, the first one is collapsed. I want to have to have multiple views expanded at the same time. Is this possible ?

**Comment by cachapa** [comment]
I don't understand the question. Each ExpandableLayout works independently from the others.

Are you referring to the recyclerview example in the repository? You can remove the logic which collapses items when another is selected.

**Comment by pierrekhouryy** [comment]
Hello, 
Thanks for your reply! And yes I am referring to the recycler view example, I don’t know how to remove the logic , and I don’t seem to find a documentation on how to do that, can you help me with that ?
Thanks a lot,
Pierre Khoury
CCE Student – USJ ESIB
+96171217377

**Comment by cachapa** [comment]
You'd be better off directing these sorts of questions to StackOverflow.
This issue tracker is intended for reporting bugs in the library, not general support.
