### ISSUE TITLE
Request: Linear layout as root.

### ISSUE THREAD

**Issue by someAndroidDeveloper** [cachapa/ExpandableLayout#83]
I think it would be better if your view extends Linear layout instead of a frame layout, since it has to do expanding and collapsing in both horizontal and vertical orientations.

**Comment by cachapa** [comment]
Better how?

**Comment by someAndroidDeveloper** [comment]
As you know a linear layout puts its children in a row/column and obviously takes more space on the screen so it makes more sense when such layout gets collapsed/expanded rather than a frame layout which stacks the children. And of course in cases like me it makes layout lighter because I had to add a direct linear layout child to get my job done.

If it's possible and you intend to do this, it's a good idea to add it as a side option within the original one.

**Comment by cachapa** [comment]
The purpose of ExpandableLayout is to expand and collapse a single view. It has nothing to do with laying multiple views horizontally or vertically.

The intended way to use this library is by wrapping the view you want to expand or collapse and dropping it inside another layout. Please look at the supplied examples.
