### ISSUE TITLE
collapse all open items, when click on one item

### ISSUE THREAD

**Issue by vipulasri** [cachapa/ExpandableLayout#9]
Is there a way to collapse all items in RecyclerView Adapter, when user clicks on one single item. That is only one item should be in expanded mode.

**Comment by cachapa** [comment]
Sure, the SimpleAdapter in the demo does just that:
https://github.com/cachapa/ExpandableLayout/blob/master/demo/src/main/java/net/cachapa/expandablelayoutdemo/
