### ISSUE TITLE
JCenter is scheduled for closing

### ISSUE THREAD

**Issue by Shoorie** [cachapa/ExpandableLayout#91]
### **Overview**

JCenter Maven repository is scheduled for closing. Migrate to other central repository.
JCenter end of life memo - https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

### **Expected**

Since Gradle 7.0 JCenter Maven repository is marked as deprecated. Library should remain available even though developer will decide to drop JCenter support.

### **Actual**

Removing JCenter from project repositories will result of ExpandableLayout library being unable to find.
The problem is connected to build system. It's not device-related.

### **Reproducible steps**

Add latest ExpandableLayout version to the project.
Having JCenter still in repository list, synchronize the project.
At this point everything should be fine.
Remove JCenter from repository list.
Synchronize the project (optionally purging local Maven repository).
Gradle synchronization will fail with "Could not resolve all files" error mentioning ExpandableLayout library.

**Comment by cachapa** [comment]
We already migrated to jitpack

**Comment by Shoorie** [comment]
Ok, but still when removing **jcenter()** from repository list I'm getting:

Execution failed for task ':application:dataBindingMergeDependencyArtifactsDevDebug'.
> Could not resolve all files for configuration ':application:devDebugCompileClasspath'.
   > Could not find net.cachapa.expandablelayout:expandablelayout:2.9.2.
     Required by:
         project :application
