### ISSUE TITLE
Unable to download dependency from Maven

### ISSUE THREAD

**Issue by VinodVPMisc** [cachapa/ExpandableLayout#98]
Hi I am getting below error in the pipeline

Cause 1: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find net.cachapa.expandablelayout:expandablelayout:2.9.2.

Seems unable download dependency from maven server. Is it correct ?

**Comment by cachapa** [comment]
Please use Jitpack: https://github.com/cachapa/ExpandableLayout#usage

**Comment by VinodVPMisc** [comment]
Thanks for the quick response :)
